create table if not exists public.workout_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  workout_key text not null check (workout_key in ('a', 'b', 'movement')),
  completed_at timestamptz not null default now(),
  unique (user_id, date)
);

create index if not exists workout_completions_user_date_idx
  on public.workout_completions (user_id, date desc);

alter table public.workout_completions enable row level security;

revoke all on table public.workout_completions from public;
revoke all on table public.workout_completions from anon;
grant select, insert, update, delete on table public.workout_completions to authenticated;

drop policy if exists "Users can view their own workout completions" on public.workout_completions;
drop policy if exists "Users can insert their own workout completions" on public.workout_completions;
drop policy if exists "Users can update their own workout completions" on public.workout_completions;
drop policy if exists "Users can delete their own workout completions" on public.workout_completions;

create policy "Users can view their own workout completions"
  on public.workout_completions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can insert their own workout completions"
  on public.workout_completions
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own workout completions"
  on public.workout_completions
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own workout completions"
  on public.workout_completions
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
